// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb,TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-RWZG-kZwIUi1EZBj7awBiqXkYFUblWE',
    appId: '1:1038627467516:web:6085d58791adaa117aa779',
    messagingSenderId: '1038627467516',
    projectId: 'quick-chat-f7d05',
    authDomain: 'quick-chat-f7d05.firebaseapp.com',
    storageBucket: 'quick-chat-f7d05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPdjcJsXO5DiPk43s_0uT4h4EPvNuB1jI',
    appId: '1:1038627467516:android:a09029ad1c50f6cc7aa779',
    messagingSenderId: '1038627467516',
    projectId: 'quick-chat-f7d05',
    storageBucket: 'quick-chat-f7d05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Noupru1ZcXJPqoJa_uRXj4rhwx7EPXc',
    appId: '1:1038627467516:ios:fff9a18d2f226d547aa779',
    messagingSenderId: '1038627467516',
    projectId: 'quick-chat-f7d05',
    storageBucket: 'quick-chat-f7d05.appspot.com',
    iosBundleId: 'com.example.quickChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Noupru1ZcXJPqoJa_uRXj4rhwx7EPXc',
    appId: '1:1038627467516:ios:fff9a18d2f226d547aa779',
    messagingSenderId: '1038627467516',
    projectId: 'quick-chat-f7d05',
    storageBucket: 'quick-chat-f7d05.appspot.com',
    iosBundleId: 'com.example.quickChat',
  );
}
